/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerServicoPnl.java
 *
 * Created on 22/08/2011, 21:08:45
 */
package LoNuevo;
 
/**
 *
 * @author usuario
 */
public class VerServicoPnl extends javax.swing.JPanel {

    /** Creates new form VerServicoPnl */
    public VerServicoPnl() {
        initComponents();
        initComponents2();

        elegirBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        String mes, dia, anio;
        dia= Integer.toString(nacimientoCalendar.getDayChooser().getDay());
        mes= Integer.toString(nacimientoCalendar.getMonthChooser().getMonth()+1);
        anio= Integer.toString(nacimientoCalendar.getYearChooser().getYear());
        fechaText.setText(dia+"/"+mes+"/"+anio);
        elegirBtn.setVisible(false);
        fechabtn.setVisible(true);
        nacimientoCalendar.setVisible(false);
        
        }
        });
    }

    
 public void initComponents2()
 {
     jComboMacho.addItem("Macho RP1");
     jComboMacho.addItem("Macho RP2");
     jComboMacho.addItem("Macho RP3");
     jComboMacho.addItem("Desconocido");
 
     jComboHembra.addItem("Hembra RP1");
     jComboHembra.addItem("Hembra RP2");
     jComboHembra.addItem("Hembra RP3");
     jComboHembra.addItem("Hembra RP4");

    nacimientoCalendar.setVisible(false);
    elegirBtn.setVisible(false);

 
 }



    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nacimientoCalendar = new com.toedter.calendar.JCalendar();
        elegirBtn = new javax.swing.JButton();
        fechabtn = new javax.swing.JButton();
        fechaText = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        jComboMacho = new javax.swing.JComboBox();
        machoLabel = new javax.swing.JLabel();
        jComboHembra = new javax.swing.JComboBox();
        hembraLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(470, 330));

        jLabel1.setText("FILTROS:");

        nacimientoCalendar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nacimientoCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nacimientoCalendarMouseClicked(evt);
            }
        });

        elegirBtn.setText("Seleccionar");
        elegirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirBtnActionPerformed(evt);
            }
        });

        fechabtn.setText("...");
        fechabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechabtnActionPerformed(evt);
            }
        });

        fechaLabel.setText("FECHA");

        jComboMacho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione" }));
        jComboMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMachoActionPerformed(evt);
            }
        });

        machoLabel.setText("RP Macho");

        jComboHembra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione" }));

        hembraLabel.setText("RP Hembra");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fechaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(hembraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboHembra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(machoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboMacho, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(nacimientoCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(300, Short.MAX_VALUE)
                        .addComponent(elegirBtn)))
                .addGap(461, 461, 461))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaLabel)
                            .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechabtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboMacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hembraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nacimientoCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elegirBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void nacimientoCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nacimientoCalendarMouseClicked
        fechaText.setText(nacimientoCalendar.getDate().toString());
}//GEN-LAST:event_nacimientoCalendarMouseClicked

    private void elegirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_elegirBtnActionPerformed

    private void fechabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechabtnActionPerformed
        nacimientoCalendar.setVisible(true);
        fechabtn.setVisible(false);
        elegirBtn.setVisible(true);
}//GEN-LAST:event_fechabtnActionPerformed

    private void jComboMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMachoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton elegirBtn;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaText;
    private javax.swing.JButton fechabtn;
    private javax.swing.JLabel hembraLabel;
    private javax.swing.JComboBox jComboHembra;
    private javax.swing.JComboBox jComboMacho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel machoLabel;
    private com.toedter.calendar.JCalendar nacimientoCalendar;
    // End of variables declaration//GEN-END:variables
}
