/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlABMServicio.java
 *
 * Created on 20/05/2013, 21:23:35
 */
package Frames;

/**
 *
 * @author usuario
 */
public class PnlABMServicio extends javax.swing.JPanel {

    /** Creates new form PnlABMServicio */
    public PnlABMServicio() {
        initComponents();
        nacimientoCalendar.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        nacimientoCalendar = new com.toedter.calendar.JCalendar();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(449, 599));
        setPreferredSize(new java.awt.Dimension(599, 449));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Servicio:");
        add(jLabel1);
        jLabel1.setBounds(12, 17, 62, 17);
        add(jTextField4);
        jTextField4.setBounds(90, 10, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Macho:");
        add(jLabel3);
        jLabel3.setBounds(12, 90, 51, 17);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(90, 80, 100, 30);
        add(jTextField3);
        jTextField3.setBounds(90, 150, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Hembra:");
        add(jLabel4);
        jLabel4.setBounds(10, 160, 58, 17);

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setText("Exito");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(250, 100, 63, 25);

        nacimientoCalendar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nacimientoCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nacimientoCalendarMouseClicked(evt);
            }
        });
        nacimientoCalendar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nacimientoCalendarKeyPressed(evt);
            }
        });
        add(nacimientoCalendar);
        nacimientoCalendar.setBounds(110, 270, 188, 133);

        jTextField1.setName("servicioFechatxt"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(90, 220, 100, 30);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(230, 220, 33, 28);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(400, 20, 120, 25);

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(400, 80, 120, 25);

        jButton3.setText("Modiificar");
        add(jButton3);
        jButton3.setBounds(400, 140, 120, 25);

        jButton5.setText("Eliminar");
        add(jButton5);
        jButton5.setBounds(400, 210, 120, 25);

        jButton6.setText("Informes");
        add(jButton6);
        jButton6.setBounds(400, 280, 120, 25);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Fecha:");
        add(jLabel2);
        jLabel2.setBounds(10, 230, 47, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nacimientoCalendar.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nacimientoCalendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nacimientoCalendarKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_nacimientoCalendarKeyPressed

    private void nacimientoCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nacimientoCalendarMouseClicked
       //jTextField1.setText(nacimientoCalendar.getDate().toString());
       
        String mes, dia, anio;
        dia= Integer.toString(nacimientoCalendar.getDayChooser().getDay());
        mes= Integer.toString(nacimientoCalendar.getMonthChooser().getMonth()+1);
        anio= Integer.toString(nacimientoCalendar.getYearChooser().getYear());
        jTextField1.setText(dia+"/"+mes+"/"+anio);
       
    }//GEN-LAST:event_nacimientoCalendarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JCalendar nacimientoCalendar;
    // End of variables declaration//GEN-END:variables
}
